GET http://127.0.0.1:3003/api/blogs/

###

POST http://127.0.0.1:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmsiLCJpZCI6IjY0YWViN2Y2ZGFjOWM0NTQ1ZDIxZTVhZiIsImlhdCI6MTY4OTI0NjA2MywiZXhwIjoxNjg5MjQ5NjYzfQ.t75i5F-FTjzEfpljB7L0L97aXqboPjOokaFKVdyuz0m

{
    "title": "Jamaican",
    "author": "Time Burton",
    "url": "www.superman.com",
    "likes": 600
}

###

DELETE http://127.0.0.1:3003/api/blogs/64af1f9e450e2a90cfeb101e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmsiLCJpZCI6IjY0YWViN2Y2ZGFjOWM0NTQ1ZDIxZTVhZiIsImlhdCI6MTY4OTI0MTA0NSwiZXhwIjoxNjg5MjQ0NjQ1fQ.wDZf0i0_POCjkUyowA4V435jKyXBPOnMhGIPk52qIBs

###

PUT http://127.0.0.1:3003/api/blogs/64ad3f91a03fc38927d3d7bd
Content-Type: application/json

{
    "title": "Batman Forever",
    "author": "Time Burton",
    "url": "www.batman.com",
    "likes": 400,
    "user": "64ad3e826d379988d338c52f"
}