GET http://127.0.0.1:3003/api/blogs/

###

POST http://127.0.0.1:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer

{
    "title": "Pablo",
    "author": "Time Burton",
    "url": "www.superman.com",
    "likes": 600
}

###

DELETE http://127.0.0.1:3003/api/blogs/64afd980024b0d458cfd744a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YWQzZTgyNmQzNzk5ODhkMzM4YzUyZiIsImlhdCI6MTY4OTY3NzA0MywiZXhwIjoxNjg5NjgwNjQzfQ.H8I-fGszsk2MFV8b43Eskd2sK8sxMXMomCSL1WbKmn4

###

PUT http://127.0.0.1:3003/api/blogs/64ad3f91a03fc38927d3d7bd
Content-Type: application/json

{
    "title": "Batman Forever",
    "author": "Time Burton",
    "url": "www.batman.com",
    "likes": 400,
    "user": "64ad3e826d379988d338c52f"
}